version: '2'
services:
  web:
    image: node:6.1
    volumes:
      - ./src/:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c 'npm install; npm install -g nodemon; nodemon -e scss,js,pug app.js'
    ports:
      - "8010:3000"
    networks: 
      - all

networks:
  all: